language: python
python:
  - "3.5"
env:
  - CARAVAN_USE_PSEUDO_FIBER=0
  - CARAVAN_USE_PSEUDO_FIBER=1
install:
  - pip install fibers
  - env NPROC=4 ./caravan_scheduler/travis/buildx10.sh
before_script:
  - export PATH=$PWD/x10/x10.dist/bin:$PATH
  - cd caravan_scheduler && ./build.sh && cd ..
script:
  - env CARAVAN_LOG_LEVEL=1 python -m unittest discover test
cache:
  directories:
  - x10/x10.dist
