language: python
python:
  - "3.6"
env:
  - NPROC=4
install:
  - pip install fibers
  - ./caravan_scheduler/travis/buildx10.sh
before_script:
  - export PATH=$PWD/x10/x10.dist/bin:$PATH
  - cd caravan_scheduler && ./build.sh && cd ..
script:
  - python -m unittest discover test
cache:
  directories:
  - x10/x10.dist
